version: '1'
services:   
  database:
    build:
      context: ./db
    ports:
      - "3306:3306"
      - "33060:33060"
    restart: always
    hostname: database
    networks:
      - mynet
    environment:
      - MYSQL_ROOT_PASSWORD=Guilherme*123
      - MYSQL_DATABASE=myself_menu
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    command: mysqld --default-authentication-plugin=mysql_native_password && mysql --default-authentication-plugin=mysql_native_password && ls && --default-authentication-plugin=mysql_native_password
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    networks:
      - mynet
    depends_on:
      - database
networks:
  mynet:
    driver: bridge